### ISSUE TITLE
SELAAAm

### ISSUE THREAD

**Issue by Zorkonn** [BTaskaya/kebabLang#3]
Gerçek hayatta hangi konularda işimize yarıyor ? bu

**Comment by BTaskaya** [comment]
String printlerken iş görüyor. 
Mesela kebabın bulunuş tarihi olan 1894'ü kebabLang ile yazabilirsin.
 ```kebabLang
tatli:baklava;
tatli:helva;
tatli:pasta;
tatli:sutlac;
```
