### ISSUE TITLE
how can I execute kebab files?

### ISSUE THREAD

**Issue by unicod3** [BTaskaya/kebabLang#6]
when i try this
`python main.py ../examples/merhaba.kebab`

I get this

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import lang,sys
  File "/Users/cnone/Projects/kebabLang/kebabLang/lang.py", line 134
    elif i.lower().startswith(self.ifstartPrefix) and ifStatus is False:
       ^
SyntaxError: invalid syntax
```

what is the proper way to compile kebab files?

**Comment by BTaskaya** [comment]
This project is literally dead, i want fixing bugs but it is worst code i have ever written. I dont suggest you to use this interpreter. 
If you want the fix it you can check travis history and find a successful commit. Then you can interpret your kebab files to strings easiy :)
